# Generated by Django 5.2.6 on 2025-09-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('grade', models.SmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.TextField()),
                ('region', models.CharField(max_length=20)),
                ('textbook_version', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
